<?php

namespace AppBundle\Repository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository
{

    public function findPaymentByUser($id = null)
    {
        if (!isset($id))
            return null;

        $qb = $this->_em->createQueryBuilder();
        $qb->select('p')
            ->from('AppBundle\Entity\Payment', 'p')
            ->where('p.user_id = :id')
            ->setParameter('id', $id);

        $query = $qb->getQuery();

        return $query->getResult();
    }


}
