app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
            _locale: en|fr|es
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"