app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
            _locale: en|fr|es

fos_user:
    resource: "fosuser_routing.yml"
    prefix:   /{_locale}/
    requirements:
            _locale: en|fr|es

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: home
        permanent: true