app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
            _locale: en|fr|es

fos_user:
    resource: "fosuser_routing.yml"
    prefix:   /{_locale}/
    requirements:
            _locale: en|fr|es

rootRedirect:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: home
        permanent: true

loginRedirect:
    path: /login
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fos_user_security_login
        permanent: true

registerRedirect:
    path: /(en|fr|es)/register/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: createUser #app public registration is forbidden
        permanent: true