# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_PROF
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_PROF:        ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout

#            logout:       true
            anonymous:    true
            switch_user: { role: ROLE_ADMIN, parameter: _want_to_be }

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_error/*, role: IS_AUTHENTICATED_ANONYMOUSLY } #dev error pages preview
        - { path: ^/(en|fr|es)/admin/, role: ROLE_PROF }
        - { path: ^/(en|fr|es)/admin/payments, role: ROLE_ADMIN }