checklist:
    path:     /admin/checklist/{courseId}
    defaults: { _controller: AppBundle:Checklist:checklist }

checklists:
    path:     /admin/checklists/
    defaults:  { _controller: AppBundle:Checklist:index }

updateChecklist:
    path:     /admin/update-checklist/
    defaults: { _controller: AppBundle:Checklist:updateChecklist }

usersChecklist:
    path:     /admin/display-checklist/{checklistId}
    defaults: { _controller: AppBundle:Checklist:displayChecklist }

deleteChecklist:
    path:     /admin/delete-checklist/{checklistId}
    defaults: { _controller: AppBundle:Checklist:deleteChecklist }