payments:
    path:     /admin/payments
    defaults: { _controller: AppBundle:Payment:index }

deletePayment:
    path:     /admin/delete-payment/{paymentId}
    defaults: { _controller: AppBundle:Payment:deletePayment }

createPayment:
    path:     /admin/create-payment/
    defaults: { _controller: AppBundle:Payment:createPayment}

updatePayment:
    path:     /admin/update-payment/
    defaults: { _controller: AppBundle:Payment:updatePayment}

updateUserPayment:
    path:     /admin/update-user-payment/
    defaults:  { _controller: AppBundle:Payment:updateUserPayment}