home:
    path:     /
    defaults: { _controller: AppBundle:Showcase:index }
gallery:
    path:     /gallery
    defaults: { _controller: AppBundle:Showcase:gallery }
contact:
    path:     /contact
    defaults: { _controller: AppBundle:Showcase:contact }
styles:
    path:     /styles
    defaults: { _controller: AppBundle:Showcase:styles }
about:
    path:     /about
    defaults: { _controller: AppBundle:Showcase:about }
timetable:
    path:     /timetable
    defaults: { _controller: AppBundle:Showcase:timetable }
privacy:
    path:     /privacy-policy
    defaults: { _controller: AppBundle:Showcase:privacy }

