home:
    path:     /
    defaults: { _controller: AppBundle:Showcase:index }
gallery:
    path:     /gallery
    defaults: { _controller: AppBundle:Showcase:gallery }
contact:
    path:     /contact
    defaults: { _controller: AppBundle:Showcase:contact }
courses:
    path:     /courses
    defaults: { _controller: AppBundle:Showcase:courses }
about:
    path:     /about
    defaults: { _controller: AppBundle:Showcase:about }