parameters:
    topbar:
        title: Administration Nouestil
    leftMenu:
        -
            icon:   fa-user
            label:  Utilisateurs
            path:   users
            scope : prof
        -
            icon:   fa-link
            label:  Contacts
            path:   contacts
            scope: prof
        -
            icon:   fa-calendar
            label:  Cours
            path:   courses
            scope: prof
        -
           icon:   fa-money
           label:  Paiements
           path:   payments
           scope: admin
        -
           icon:   fa-list
           label:  Listes d'appel
           path:   payments
           scope: prof