users:
    resource: '@AppBundle/Resources/config/routing/users.yml'

payments:
    resource: '@AppBundle/Resources/config/routing/payments.yml'

showcase:
    resource: '@AppBundle/Resources/config/routing/showcase.yml'

teachers:
    resource: '@AppBundle/Resources/config/routing/teachers.yml'
