services:

    nouestil.user:
            class: AppBundle\Manager\UserManager
            arguments:
                - '@doctrine.orm.entity_manager'

    nouestil.payment:
            class: AppBundle\Manager\PaymentManager
            arguments:
                - '@doctrine.orm.entity_manager'

    nouestil.course:
            class: AppBundle\Manager\CourseManager
            arguments:
                - '@doctrine.orm.entity_manager'